# Generated by Django 3.1.4 on 2020-12-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_movierating_userrequestcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='rating',
            field=models.FloatField(),
        ),
    ]
